/*
 * awesome-personal-list - README.md rendering.
 * Grouped by category (alphabetical, empty categories skipped), each entry
 * just the original repo plus its Software Heritage status -- no mirror
 * link, per the whole point of this app.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <time.h>

#include "app.h"
#include "helpers.h"
#include "models.h"
#include "readme.h"
#include "wbuf.h"
#include "xmalloc.h"

static int
cmp_category_name(const void *a, const void *b)
{
	const struct category	*ca = a, *cb = b;

	return (strcasecmp(ca->name, cb->name));
}

static int
cmp_source_url(const void *a, const void *b)
{
	const struct source	*sa = a, *sb = b;

	return (strcasecmp(sa->original_url, sb->original_url));
}

/*
 * The checker writes results to swh_cache.tsv, keyed on original_url; that
 * is the live status. The copy on the source record is only what was known
 * at import time, and is the fallback when the checker hasn't run yet.
 */
static void
append_source(struct wbuf *out, const struct source *s)
{
	char	*enc;
	char	 checked[32];
	int	 status;
	time_t	 checked_at;

	if (swh_cache_get(s->original_url, &status, &checked_at) == -1) {
		status = s->swh_status;
		checked_at = s->swh_checked_at;
	}

	wbuf_appendf(out, "- **[%s](%s)**", repo_display_name(s->original_url),
	    s->original_url);

	if (s->description[0] != '\0')
		wbuf_appendf(out, " — %s", s->description);

	buf_lit(out, "\n  ");

	enc = url_encode_str(s->original_url);

	switch (status) {
	case SWH_STATUS_ARCHIVED:
		wbuf_appendf(out,
		    "✅ [Archived in Software Heritage]"
		    "(https://archive.softwareheritage.org/browse/origin/"
		    "?origin_url=%s)", enc);
		break;
	case SWH_STATUS_NOT_FOUND:
		fmt_date(checked_at, checked, sizeof(checked));
		wbuf_appendf(out, "⚠️ Not foundain Software Heritage as of %s", checked);
		break;
	default:
		buf_lit(out, "❔ Not checked yet");
	}

	free(enc);
	buf_lit(out, "\n\n");
}

char *
readme_render(void)
{
	struct wbuf		 out;
	struct source		*srcs;
	struct category		*cats;
	size_t			 nsrc, ncat, i, j;
	time_t			 now;
	char			 stamp[32];

	wbuf_init(&out, 8192);

	buf_lit(&out, "# Awesome Mirrors\n\n");

	now = time(NULL);
	strftime(stamp, sizeof(stamp), "%Y-%m-%d", gmtime(&now));
	wbuf_appendf(&out, "_Generated by " APP_NAME " on %s._\n\n", stamp);

	if (category_list(&cats, &ncat) == -1 || source_list(&srcs, &nsrc) == -1) {
		buf_lit(&out, "_(nothing to render)_\n");
		return (wbuf_stringify(&out, NULL));
	}

	qsort(cats, ncat, sizeof(*cats), cmp_category_name);
	qsort(srcs, nsrc, sizeof(*srcs), cmp_source_url);

	/* A source in several categories (e.g. C + SDL) appears under each. */
	for (i = 0; i < ncat; i++) {
		int	any = 0;

		for (j = 0; j < nsrc; j++) {
			if (source_has_category(&srcs[j], cats[i].slug)) {
				any = 1;
				break;
			}
		}

		if (!any)
			continue;

		wbuf_appendf(&out, "## %s\n\n", cats[i].name);

		for (j = 0; j < nsrc; j++) {
			if (source_has_category(&srcs[j], cats[i].slug))
				append_source(&out, &srcs[j]);
		}
	}

	category_list_free(cats);
	source_list_free(srcs);

	return (wbuf_stringify(&out, NULL));
}
